name: ht_dart_exporter
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: 1.1.0
  args: 2.0.0
  hetu_script: 0.0.3
  json_annotation: 4.0.0
#  path: ^1.7.0

dev_dependencies:
  json_serializable: 4.0.2
  pedantic: ^1.9.0
  test: ^1.14.4
