name: hetu_binding_generator
description: A binding-code generator for Hetu script language. You can generate glue codes from Flutter/Dart library, your own codes, or any packages. Then you can use them in the Hetu script.
version: 1.0.17
homepage: https://github.com/hetu-script/hetu-script-autobinding

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^2.8.0
  args: ^2.3.0
  json_annotation: ^4.3.0
  mustache_template: ^2.0.0

dev_dependencies:
  json_serializable: ^6.0.1
  lints: ^1.0.1
  test: ^1.19.4
